ErrorCode 클래스에서 Code를 변경했습니다.
woowacourse-teams/2020-14f-guys pull request #247
Opened 2020-08-18 07:48 UTC by KIMSIYOUNG

메시지가 맘에 안드실 수 있어요!
좋은 메세지 있으면 `아니`  라는 대답과 이유 혹은 대안을 제시해주면 좋을 것 같습니다😊

resolves #154

2020-08-19 12:15 UTC, fucct requested changes
수고하셨습니다.

2020-08-19 12:15 UTC, fucct commented on peloton-frontend/utils/api/MemberApi.js
> +          Authorization: `Bearer ${token}asdasd`,
삭제해야할 것 같아요

2020-08-19 12:15 UTC, fucct commented on peloton-frontend/component/home/homemain/RaceList.js
> +        alert(error.response.data.code);
에러상황에 있어 alert는 사용자에게, console.log는 관리자에게 메세지를 제공할텐데, alert에는 code에 대한 사용자 메세지를, log에는 개발자가 보고 사용할 수 있는 진짜 메세지를 보여준다면 좀 더 이용하기 편할 것 같아요.

2020-08-20 16:02 UTC, KIMSIYOUNG commented on peloton-frontend/component/home/homemain/RaceList.js
> +        alert(error.response.data.code);
모든 정보를 보여주면 좋을 것 같긴 하지만 이 부분은 선택적으로 프론트엔드 개발자가 확인하면 될 것 같아서 
프론트엔드 개발자는 ErrorCode의 Message를, (ex Member(member id : 1) not exist)
일반 사용자는 ErrorCode의 Code를 보여주는 형태로 변경하였습니다.

2020-08-20 23:57 UTC, JinJuMoon approved these changes

2020-08-21 01:52 UTC, merged