refactor: 로그아웃, 삭제, 프로필이미지 업로드 수정했습니다.
woowacourse-teams/2020-14f-guys pull request #251
Opened 2020-08-18 14:16 UTC by fucct

수정 내역은 다음과 같습니다.

- Logout & Sign out 시 모든 상태를 날리도록 수정했습니다. 
- 가입 후 카카오톡 프로필 사진을 정상적으로 불러오도록 수정했습니다.
- 프로필 사진에 수정 버튼 위치를 적절하게 수정했습니다.
- 프로필 사진 수정 시 실제 요청이 전송되는 시점을 다음 버튼을 누르는 순간으로 변경했습니다.

2020-08-18 14:23 UTC, JinJuMoon commented on peloton-frontend/component/LoginNavigationRoot.js
> +        options={{ headerShown: false}}
공백이 잘못 지워진 것 같아요!

2020-08-18 14:38 UTC, JinJuMoon commented on peloton-frontend/component/profile/ProfileImage.js
> +          ? { uri: memberInfo.profile }
memberInfo가 없을 때는 어떤 경우인가요? 로딩 중인 경우는 defaultSource에서 설정이 되어있어요!

2020-08-18 14:41 UTC, JinJuMoon commented on peloton-frontend/component/profile/ProfileImageEditButton.js
> +const ProfileImageEditButton = ({ children, directUpdate }) => {
컴포넌트를 재활용하도록 리팩토링 👍

2020-08-18 15:43 UTC, fucct commented on peloton-frontend/component/profile/ProfileImage.js
> +          ? { uri: memberInfo.profile }
memberInfo가 Promise Pending 상태인 경우 정상적으로  이미지 렌더를 못하고 에러가 나더라고요. 가급적이면 모든 Image에 대해서 이 경우를 미연에 방지하고자 추가했습니다.

2020-08-19 04:15 UTC, JinJuMoon approved these changes

2020-08-19 05:01 UTC, dks301 requested changes
수고하셨습니다.
프로필 이미지 바꾸면 로딩 인디케이터가 터치 전에 안사라지는 버그가 있어요

2020-08-19 07:37 UTC, JinJuMoon approved these changes

2020-08-19 08:03 UTC, dks301 approved these changes
일단 approve하겠습니다 :)
제 폰에서 발생하는 버그는 제가 이슈로 올려놓겠습니다.

2020-08-19 08:19 UTC, dks301 approved these changes

2020-08-19 11:07 UTC, JinJuMoon approved these changes

2020-08-19 11:08 UTC, merged

2020-08-19 13:58 UTC, fucct commented
resolves #255