feat: 인증 생성 기능 구현
woowacourse-teams/2020-14f-guys pull request #252
Opened 2020-08-19 06:45 UTC by ddaaac

2020-08-19 09:50 UTC, dks301 requested changes
수고하셨습니다 👍 

백엔드 부분은 크게 남길 게 없네요.
프론트는 로직이 ISO UTC기준으로 되어있어서 #253 이 머지되면 다시 한번 확인해 볼 필요가 있을 것 같아요 :)
그리고 인증 이미지를 업로드 할 때 로딩 인디케이터가 여기서도 사라지지 않네요 ㅋㅋ 한 번 확인해주세요

2020-08-19 09:50 UTC, dks301 commented on peloton-frontend/component/certification/Certification.js
> +      })();
42번째 줄에 String.valueOf 밖에 값을 넣어주네요

2020-08-19 09:50 UTC, dks301 commented on peloton-frontend/component/certification/Certification.js
> +        const { upcoming_missions } = await QueryApi.getMissions(token);
서버랑 통신하는 부분은 try catch를 이용해서 예외처리를 해주면 좋을 것 같아요

2020-08-19 09:50 UTC, dks301 commented on peloton-frontend/component/certification/CertificationItem.js
> +      return navigateToCertificate(false);
이 부분은 아니지만 raceItem의 title이 길면 상자가 화면을 다 차지하네요 😨

2020-08-19 09:50 UTC, dks301 commented on peloton-frontend/component/certification/CertificationSubmit.js
>        alert(e.response.data.message);
인증 완료한 사진에대해서 다시한 번 인증사진을 업로드할 때 alert만 뜨고 메시지가 뜨지 않아요
저만 이런 걸 수도 있으니 한 번 확인해주세요

2020-08-19 09:50 UTC, dks301 commented on peloton-frontend/utils/api/CertificationApi.js
> +    const { headers } = await Axios.post(
try catch

2020-08-19 09:50 UTC, dks301 commented on peloton-frontend/utils/api/QueryApi.js
> +    const response = await Axios({
try catch

2020-08-19 12:12 UTC, JinJuMoon requested changes
몇가지 간단한 코멘트 남겼으니 확인해주세요~

2020-08-19 12:12 UTC, JinJuMoon commented on src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationRequest.java
> +public class CertificationRequest {
create용 request와 update용 request는 분리가 필요하지 않을까요?
추후에 차이점이 명확해졌을 때 분리하려고 의도하신 거라면 이 코멘트는 넘어가셔도 됩니다 :)

2020-08-19 12:12 UTC, JinJuMoon commented on src/test/java/com/woowacourse/pelotonbackend/certification/presentation/CertificationControllerTest.java
> +    @DisplayName("정상 update request에 대한 수정")
"정상적인 요청에 대해 Certification을 수정한다"는 어떨까요?

2020-08-19 12:12 UTC, JinJuMoon commented on src/test/java/com/woowacourse/pelotonbackend/certification/CertificationAcceptanceTest.java
> +    // TODO: 인수테스트 작성하기
이번에 변경된 부분은 아니지만 CertificationAcceptanceTest가 2개예요

2020-08-19 12:32 UTC, ddaaac commented on peloton-frontend/component/certification/Certification.js
> +      })();
원래 저런 문법이긴 한데, 그냥 toString()으로 변경했습니다.

2020-08-19 12:33 UTC, ddaaac commented on peloton-frontend/component/certification/CertificationItem.js
> +      return navigateToCertificate(false);
인지하고 있는 부분이긴 한데, UI적으로 어떻게 해야할지 몰라서 놔두고 있습니다.
어떻게 해야 좋을까요?

2020-08-19 12:34 UTC, ddaaac commented on peloton-frontend/component/certification/CertificationSubmit.js
>        alert(e.response.data.message);
백엔드 커밋이 같이 머지돼야 확인할 수 있습니다.
Certification Put 메서드가 없더라고요

2020-08-19 12:36 UTC, ddaaac commented on peloton-frontend/utils/api/CertificationApi.js
> +    const { headers } = await Axios.post(
api 내부에서 try catch로 잡으면 외부에서 에러 메세지를 확인하는 과정이 복잡해집니다. 이를 사용하는 메서드에서는 예외 처리를 해주고 있습니다.

2020-08-19 12:41 UTC, ddaaac commented on src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationRequest.java
> +public class CertificationRequest {
Rest api에서 PUT 메서드는 모든 필드를 다 채워서 보내는 것을 규약으로 합니다. 이번에 만든 update 메서드도 이와 동일한 목적을 갖고 만들었는데, 이 경우 create과 update의 dto가 다를 필요가 없을 것 같아서 합쳤습니다. 나중에 논의해봐도 좋을 것 같네요 :)

2020-08-19 12:42 UTC, ddaaac commented on src/test/java/com/woowacourse/pelotonbackend/certification/CertificationAcceptanceTest.java
> +    // TODO: 인수테스트 작성하기
뭐죠...

2020-08-19 14:33 UTC, ddaaac commented
현재 CertificationAcceptanceTest에는 두가지 문제가 있습니다.

하나는 #259 에 관한 문제로, 인증의 description 필드를 아예 사용하는게 불가능한 버그입니다.
다른 하나는 인수테스트를 돌렸을 때, 인증의 update 시 이미지를 aws에 업로드할 때 발생하는 문제입니다.
![image](https://user-images.githubusercontent.com/43440195/90648335-5b0ec600-e274-11ea-9c87-36a8958976e7.png)

Aws Sdk 예외가 발생하는 것인데 지금까지 알아본 바로는 [링크](https://github.com/aws/aws-sdk-java/issues/2365)를 참고하면 sdk 버전문제인 것 같습니다.
업로드 자체는 문제없이 되는 것으로 보아 심각한 문제는 아닌 것 같은데, 머지가 되고 바로 테스트를 해보겠습니다.

2020-08-20 04:35 UTC, JinJuMoon approved these changes

2020-08-20 04:44 UTC, dks301 commented on peloton-frontend/component/certification/CertificationItem.js
> +      return navigateToCertificate(false);
일단은 UI적으로 오른쪽에 인증 대기나 인증 완료를 가리지 않는 선에서 최대값을 설정해 놓는 정도로 하면 될 것 같아요

2020-08-20 05:11 UTC, dks301 approved these changes
수고하셨습니다 :)

2020-08-20 05:16 UTC, JinJuMoon approved these changes

2020-08-20 05:23 UTC, merged