feat: 레이스 상세정보 조회 기능 구현
woowacourse-teams/2020-14f-guys pull request #256
Opened 2020-08-19 11:05 UTC by JinJuMoon

레이스 상세정보 화면에서 필요한 정보를 한꺼번에 불러오는 API를 구현했습니다.
프론트 작업은 별도의 브랜치에서 진행할 예정입니다.

2020-08-19 11:42 UTC, ddaaac requested changes
잘 구현해주셔서 딱히 남길 리뷰가 없네요

2020-08-19 11:42 UTC, ddaaac commented on src/main/java/com/woowacourse/pelotonbackend/query/presentation/dto/RaceDetailResponse.java
> +    private final DateTimeDuration missionDuration;
미션 시작 시간 ~ 종료 시간은 `LocalDateTime`보다 `LocalTime`이 더 적절하지 않을까요?
마침 저희 코드에는 `TimeDuration`이라는 값 객체가 존재하네요

2020-08-19 11:42 UTC, ddaaac commented on src/test/java/com/woowacourse/pelotonbackend/docs/QueryDocumentation.java
> +                    .attributes(getDateFormat())
시작 시간~종료 시간은 `yyyyMMdd` 포맷이 아닐 것 같아요

2020-08-19 12:41 UTC, JinJuMoon commented on src/main/java/com/woowacourse/pelotonbackend/query/presentation/dto/RaceDetailResponse.java
> +    private final DateTimeDuration missionDuration;
반영했습니다~

2020-08-19 12:41 UTC, JinJuMoon commented on src/test/java/com/woowacourse/pelotonbackend/docs/QueryDocumentation.java
> +                    .attributes(getDateFormat())
반영했습니다~

2020-08-19 13:03 UTC, ddaaac approved these changes

2020-08-20 04:46 UTC, KIMSIYOUNG requested changes
안녕하세요 무늬! 
궁금한게 있는데 기존에 있는 RaceResponse에 TimeDuration만 추가해서 처리하는 방법 대신
새로 만든 이유가 있을까요? 

개인적으로는 RaceResponse에 TimeDuration만 추가하는 방향으로 해도 충분히 해결되지 않을까싶어서요!

2020-08-20 04:46 UTC, KIMSIYOUNG commented on src/main/java/com/woowacourse/pelotonbackend/query/application/QueryService.java
> +        final Race race = raceRepository.findById(raceId).orElseThrow(() -> new RaceNotFoundException(raceId));
줄바꿈이 orElse에서 이뤄지면 좋을 것 같아요.

2020-08-20 04:46 UTC, KIMSIYOUNG commented on src/test/java/com/woowacourse/pelotonbackend/query/application/QueryServiceTest.java
> +            () -> assertThat(raceDetail).isEqualToComparingOnlyGivenFields(race, "id", "title", "description", "thumbnail", "certificationExample", "category", "entranceFee", "raceDuration"),
겹치지 않는 부분을 빼는게 가독성에 좋지 않을까요?

2020-08-20 04:54 UTC, JinJuMoon commented on src/test/java/com/woowacourse/pelotonbackend/query/application/QueryServiceTest.java
> +            () -> assertThat(raceDetail).isEqualToComparingOnlyGivenFields(race, "id", "title", "description", "thumbnail", "certificationExample", "category", "entranceFee", "raceDuration"),
race와 raceDetail의 타입이 달라서 말씀하신 메서드는 적용이 안되서 위의 메서드를 사용했습니다~

2020-08-20 04:55 UTC, JinJuMoon commented on src/main/java/com/woowacourse/pelotonbackend/query/application/QueryService.java
> +        final Race race = raceRepository.findById(raceId).orElseThrow(() -> new RaceNotFoundException(raceId));
수정했습니다~

2020-08-20 05:30 UTC, ddaaac approved these changes

2020-08-20 06:02 UTC, KIMSIYOUNG approved these changes

2020-08-20 06:02 UTC, merged