프론트 정산 페이지 구현
woowacourse-teams/2020-14f-guys pull request #289
Opened 2020-08-24 07:08 UTC by JinJuMoon

리팩토링은 우선 배제하고 구현했습니다 😢

2020-08-24 07:44 UTC, KIMSIYOUNG requested changes
간단한 리뷰 남겼어요!
예쁘게 잘 만드신거 같은데 버그아닌 버그가 있는 것 같아서 그 부분만 수정하면 좋을 것 같아요!
- POST요청은 Navigate하기 전에 하면 해결될 것 같아요.
- 사용자에게 보여주는 예외는 message가 아니라 code를 사용해주세요!
- 이제 개발이 다 된 것 같으니 주석은 제거해주세요.

2020-08-24 07:44 UTC, KIMSIYOUNG commented on peloton-frontend/component/home/race/CalculationResult.js
> +  useEffect(() => {
불필요한 주석은 삭제해주세요😀

2020-08-24 07:44 UTC, KIMSIYOUNG commented on peloton-frontend/component/home/race/RaceCalculation.js
> +        alert(e.response.data.message);
사용자가 보는 메시지는 `e.response.data.code` 를 사용해주세요.

2020-08-24 07:44 UTC, KIMSIYOUNG commented on peloton-frontend/component/home/race/RaceCalculation.js
> +    console.log("------");
주석 삭제!

2020-08-24 07:44 UTC, KIMSIYOUNG commented on peloton-frontend/component/home/race/RaceCalculation.js
> +        console.log("--");
여기도 있어요! log 검색해서 한번에 쭉 삭제 해주세요ㅎㅎ

2020-08-24 07:44 UTC, KIMSIYOUNG commented on peloton-frontend/component/home/race/RaceDetail.js
> +    navigateWithHistory(navigation, [
현재 정산하기 POST 요청이 RaceCalculation 클래스에 있어서, 만약 레이스가 진행중인 경우에 정산하기를 누르면 화면이 두번 이동해요! (정산된 페이지 갔다가, 다시 슥 돌아오게 되네요)
POST 요청을 RaceDetail로 옮기고 요청이 성공하면 네비게이트를 시키면 해결할 수 있을 것 같아요!

2020-08-24 07:44 UTC, KIMSIYOUNG commented on peloton-frontend/utils/api/CalculationApi.js
> +export const CalculationApi = {
👍

2020-08-24 07:44 UTC, KIMSIYOUNG commented on peloton-frontend/component/home/race/RaceDetail.js
> +    navigateWithHistory(navigation, [
이 부분을 이동시키면, POST 요청에서 예외가 나면(이미 정산되었다면) `결과 페이지로 이동할게요!` 라고 Alert도 같이 띄워 줄 수 있을 것 같아요.

2020-08-24 12:02 UTC, dks301 requested changes
수고하셨습니다.
리팩토링은 나중에 진행해야 할 것 같네요 ㅋㅋ
코멘트 남겼으니 확인 부탁해요 :)

2020-08-24 12:02 UTC, dks301 commented on peloton-frontend/component/home/race/RaceDetail.js
> +      alert(e.response.data.code),
alert은 Alert.alert("", e.reponse.data.code) 로 수정해주세요
앞의 빈 문자열은 title이 들어갈 위치입니다.

2020-08-25 07:20 UTC, ddaaac commented
This issue has been moved to #299

2020-08-25 07:20 UTC, closed without merging