feat: 성취율 프론트 페이지 구현
woowacourse-teams/2020-14f-guys pull request #291
Opened 2020-08-24 11:25 UTC by fucct

프로필 탭에서 성취율 보이도록 구현완료했습니다.

2020-08-24 14:16 UTC, dks301 requested changes
수고하셨습니다.
리로드가 안되는 부분은 이슈화해서 나중에 추가할 필요가 있을 것 같아요 :)
피드백 남겼으니 확인해주세요

2020-08-25 08:38 UTC, ddaaac approved these changes
걱정되는 부분은 프로필ㅇ에 minHeight를 적용시켰을 때, 핸드폰이 작다면 깨질수도 있는 부분인 것 같은데
이 부분은 수정하기 쉽게 되어있는 것 같아서 나중에 테스트할 때, 봐야될 것 같네요
딱히 리뷰남길게 없어서 어프루브 하겠습니다.

2020-08-25 08:49 UTC, fucct commented on peloton-frontend/component/profile/profiledetail/AchievementItems.js
> +      {achievementRates.map((achievementRate) => (
수정했습니다

2020-08-25 13:32 UTC, dks301 approved these changes
수고하셨습니다 👍

2020-08-25 13:47 UTC, merged