feat: 정산 프론트 페이지 구현
woowacourse-teams/2020-14f-guys pull request #299
Opened 2020-08-25 05:27 UTC by fucct

어색한 부분 리뷰 부탁드려요

2020-08-25 08:13 UTC, ddaaac requested changes

2020-08-25 08:13 UTC, ddaaac commented on peloton-frontend/component/home/race/RaceDetail.js
> +      response = await CalculationApi.post(token, raceId);
```suggestion
      const {status} = await CalculationApi.post(token, raceId);
```
post가 response.status가 아닌 response까지만 리턴하고 여기서 status를 받아쓰면 좋겠네요.
그리고 아래 if문도 try 문 안에 넣으면 될 것 같아요

2020-08-25 08:13 UTC, ddaaac commented on peloton-frontend/component/home/race/RaceDetail.js
> +    }
여기도 마찬가지고요

2020-08-25 08:13 UTC, ddaaac commented on peloton-frontend/component/home/race/RaceDetail.js
> +        <View style={styles.calculationButton}>
제 생각에는 레이스가 종료되지 않았다면 아예 안보여주는 게 좋을 것 같아요.

레이스가 종료되는 시점은 `raceInfo.race_duration.end_date`와 `raceInfo.mission_duration.end_time`을 조합하면 얻을 수 있겠네요(변수명은 조금 다를 수도 있어요)
두 정보를 합치면 UTC 시간 기준으로 끝나는 시간이 나오는데, 현재 시간이 그 시간 뒤인지 체크하면 될 것 같아요.
moment.js 라이브러리가 들어와있으니 좀 더 쉽게 할 수 있을 거라 생각됩니다. 다른 파일에 비슷한 기능이 구현된 코드도 있구요.

2020-08-25 08:19 UTC, fucct commented on peloton-frontend/component/home/HomeNavigationRoot.js
> +          headerLeft: () => <GoBackButton />,
버튼 디자인은 다음 풀리퀘에서 수정했습니다. 기본 버튼으로 수정했습니다.

2020-08-25 10:44 UTC, ddaaac requested changes

2020-08-25 10:44 UTC, ddaaac commented on peloton-frontend/component/home/race/RaceDetail.js
> +      );
이 부분 시간이 UTC로 안들어갑니다. 확인해주세요~
그리고 백틱 사용을 생활화 합시다.

2020-08-25 14:55 UTC, ddaaac approved these changes

2020-08-26 04:38 UTC, ddaaac approved these changes

2020-08-26 05:22 UTC, ddaaac approved these changes

2020-08-26 05:24 UTC, merged