feat: 캐싱 기능 구현했습니다.
woowacourse-teams/2020-14f-guys pull request #323
Opened 2020-09-21 01:48 UTC by ddaaac

resolves #322

2020-09-28 14:13 UTC, KIMSIYOUNG requested changes
어려운 레디스도 잘 구현해주셨네요.
라이더와 미션도 캐싱 적용하기 좋은 도메인이라 생각하는데 어떻게 생각하세요?
추가로 캐싱이 적용되지 않은 부분에 대해서도 테스트를 추가해주면 이해하기 좋을 것 같아요.

2020-09-28 14:13 UTC, KIMSIYOUNG commented on src/main/java/com/woowacourse/pelotonbackend/config/CacheConfig.java
> +
띄어쓰기!

2020-09-28 14:13 UTC, KIMSIYOUNG commented on src/main/java/com/woowacourse/pelotonbackend/calculation/domain/Calculation.java
> +@Table
어노테이션 위치!

2020-09-28 14:13 UTC, KIMSIYOUNG commented on src/main/java/com/woowacourse/pelotonbackend/config/JdbcConfig.java
> +    excludeFilters = @ComponentScan.Filter(type = FilterType.REGEX, pattern = "com.woowacourse.pelotonbackend.*")
레디스 관련된 요청은 필터를 안거치는 건가요? 
로그를 안 남기기 위함인가요 아니면, 아예 필터에 올 필요가 없어서인가요?

2020-09-28 14:13 UTC, KIMSIYOUNG commented on src/main/java/com/woowacourse/pelotonbackend/member/application/MemberService.java
> +    @CacheEvict(value = "member", key = "#id")
회원 API에 대한 캐쉬 결과도 테스트해주면 좋을 것 같아요!
캐쉬를 거는 곳마다 테스트 할 필요는 없는거 같긴한데 지금 테스트는 조금 부족한 것 같아요!

2020-09-28 14:13 UTC, KIMSIYOUNG commented on src/test/java/com/woowacourse/pelotonbackend/calculation/acceptance/CalculationAcceptanceTest.java
> +
캐쉬를 적용하지 않은 요청들은 경과시간이 비슷하다라는 테스트도 같이 있으면 더 좋을 것 같아요

2020-09-28 14:13 UTC, KIMSIYOUNG commented on src/test/java/com/woowacourse/pelotonbackend/support/AcceptanceTest.java
> +    protected long getElapsedTime(final Executable executable) {
멋진 표현식이네요.

2020-10-07 14:10 UTC, ddaaac commented on src/main/java/com/woowacourse/pelotonbackend/config/JdbcConfig.java
> +    excludeFilters = @ComponentScan.Filter(type = FilterType.REGEX, pattern = "com.woowacourse.pelotonbackend.*")
이 어노테이션은 `CrudRepository`를 구현체를 빈에 등록할 때 사용됩니다.
Spring Data Jdbc는 `CrudRepository`의 구현체로 `SimpleJdbcRepository`를 제공하고 Spring Data Redis는 `SimpleKeyValueRepository`를 제공합니다.

그런데 Spring data redis를 의존성에 추가하면서 같은 인터페이스의 구현체가 2개가 생겨버려서 빈 등록이 되지 않는 문제가 생겼습니다. 그래서 기존에 사용하던 JdbcRepository를 그대로 사용하고 RedisRepository는 빈 등록 대상에서 제거해서 해결했습니다

2020-10-07 15:49 UTC, ddaaac commented on src/test/java/com/woowacourse/pelotonbackend/calculation/acceptance/CalculationAcceptanceTest.java
> +
비슷하다라는게 참 애매한 표현인 것 같습니다.
아무래도 컴퓨터 사양마다 테스트 통과여부가 결정될 수 있어서 다른 방식으로 캐싱이 되는지 안되는지 테스트 케이스를 추가했습니다!

2021-07-21 08:42 UTC, merged